### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by kolaente** [knqyf263/trivy#11]
Hey there, great project!

Maybe I've overlooked it, but do you think it would be possible to provide trivy in a docker image to be able to run it in eg. [Drone}(https://drone.io/)? Or is that difficult because of the way trivy analyzes docker images?

**Comment by 030** [comment]
```
user@host:~$ docker run -it -v /var/run/docker.sock:/var/run/docker.sock knqyf263/trivy:0.0.13 utrecht/bcbsn:2.0.0
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"utrecht/bcbsn:2.0.0\": stat utrecht/bcbsn:2.0.0: no such file or directory": unknown.
```

**Comment by masahiro331** [comment]
m_fujimura [10:00 AM]
Change dockerfile CMD to ENTRYPOINT

Please use this command.

```docker run -v /var/run/docker.sock:/var/run/docker.sock  knqyf263/trivy:0.0.14 utrecht/bcbsn:2.0.0```

If you use macOS, you can use local cache below command.

```docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ knqyf263/trivy:0.0.14  utrecht/bcbsn:2.0.0```

**Comment by knqyf263** [comment]
@kolaente You can use `Trivy` in a docker container. Please specify `knqyf263/trivy:latest` or `knqyf263/trivy:0.0.14` as an image name.
https://cloud.docker.com/u/knqyf263/repository/docker/knqyf263/trivy

**Comment by 030** [comment]
The analysis works now:

```
[user@localhost ~]$ docker run -v /var/run/docker.sock:/var/run/docker.sock knqyf263/trivy:0.0.14 utrecht/bcbsn:2.0.0
Unable to find image 'knqyf263/trivy:0.0.14' locally
0.0.14: Pulling from knqyf263/trivy
e7c96db7181b: Pull complete 
a62117a94668: Pull complete 
fd4ece22b6c2: Pull complete 
Digest: sha256:93b57cd8593c7a0c334b542951bdc62f16f2afdcc2e353ac5e2d532ba6d0f3ee
Status: Downloaded newer image for knqyf263/trivy:0.0.14
2019-05-19T10:25:32.818Z	INFO	Updating vulnerability database...
2019-05-19T10:28:24.555Z	INFO	Updating NVD data...
 122550 / 122550  100.00% 2m18ss
2019-05-19T10:30:43.000Z	INFO	Updating Alpine data...
 11119 / 11119  100.00% 11s1s
2019-05-19T10:30:55.245Z	INFO	Updating RedHat data...
 19426 / 19426  100.00% 24s01s
2019-05-19T10:31:19.809Z	INFO	Updating Debian data...
 27809 / 27809  100.00% 30s01s
2019-05-19T10:31:50.674Z	INFO	Updating Debian OVAL data...
 59642 / 59642  100.00% 2m17ss
2019-05-19T10:34:07.811Z	INFO	Updating Ubuntu data...
 30191 / 30191  100.00% 1m13ss
2019-05-19T10:35:23.654Z	FATAL	error in image scan: failed to scan image: failed to analyze OS: Unknown OS
```

**Comment by 030** [comment]
When I run it for the second time, the scan takes still a while. What folder should be mounted to prevent this?

**Comment by lomycisw** [comment]
@030 
Create DB at the first start, and use cache after the second.
To use cache with docker, mount the cache directory.Create DB at the first start, and use cache after the second.
To use cache with docker, mount the cache directory.

Example for macOS:

```
docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ knqyf263/trivy:0.0.14 utrecht/bcbsn:2.0.0
```

Other case: 
Please check your OS default cache directory.

**Comment by masahiro331** [comment]
@030
Create DB at the first start, and use cache after the second.
To use cache with docker, mount the cache directory.Create DB at the first start, and use cache after the second.
To use cache with docker, mount the cache directory.

Example for macOS:

docker run -v /var/run/docker.sock:/var/run/docker.sock -v $HOME/Library/Caches:/root/.cache/ knqyf263/trivy:0.0.14 utrecht/bcbsn:2.0.0
Other case:
Please check your OS default cache directory.

**Comment by 030** [comment]
@masahiro331 I think it is useful to add this to the README.md as well

**Comment by masahiro331** [comment]
@030 
Please check here.
https://github.com/knqyf263/trivy#docker

Today added to README.md
https://github.com/knqyf263/trivy/commit/2f7f1f8e839e2996bb58c1f0ddcee6fef83f2c8c

**Comment by kolaente** [comment]
@knqyf263  @masahiro331 Great, thanks"

**Comment by knqyf263** [comment]
If you have any questions, please reopen this issue. Thanks.
