### ISSUE TITLE
Ubuntu Cosmic package

### ISSUE THREAD

**Issue by rgarrigue** [knqyf263/trivy#13]
Hi

Maybe you're focusing on LTS release, but since it's a single binary, having an Ubuntu Cosmic release shouldn't be a problem ? 

Best regards,

**Comment by SuperSandro2000** [comment]
You can use bionic for now.

**Comment by knqyf263** [comment]
Are you talking about the following section?
https://github.com/knqyf263/trivy#debianubuntu

It is divided for the future, but since it is all the same binary, it can be installed even if you specify bionic.

**Comment by rgarrigue** [comment]
I did used bionic. Thanks.
