### ISSUE TITLE
Json output change array name

### ISSUE THREAD

**Issue by hijak** [knqyf263/trivy#16]
Hi

Having the image as the array name in the json output makes it difficult for me to automate html from the json output using something like mustache

can we have the image key (and maybe some more kewl infos) seperate to the vunerablities array?

**Comment by knqyf263** [comment]
@hijak Thank you for the report. I know that problem. What format is easy to use? Let me know a sample of JSON.

**Comment by hijak** [comment]
Hi

Thanks for getting back to me something like the following layout would be useful to me at least

```
  "Image": "image/name",
  "OSversion": "alpine 3.8.2",
  "application": "symfony", <--- not sure if this is possible but i see you can do app depenancy scanning
  "Vulnerabilities": [
    {
      "VulnerabilityID": "",
      "PkgName": "",
      "InstalledVersion": "",
      "FixedVersion": "",
      "Title": "",
      "Description": "",
      "Severity": "",
      "References": []
    }
```

**Comment by knqyf263** [comment]
@hijak Thanks for suggesting the format. There may be multiple lock files. So, it needs to be an array or map.
How about the following format?

```
[
  {
    "Target": "image/name (alpine 3.8.2)",
    "Vulnerabilities": [
      {
        "VulnerabilityID": "",
        "PkgName": "",
        "InstalledVersion": "",
        "FixedVersion": "",
        "Title": "",
        "Description": "",
        "Severity": "",
        "References": []
      }
    ]
  },
  {
    "Target": "/app/Gemfile.lock",
    "Vulnerabilities": [
      {
        "VulnerabilityID": "",
        "PkgName": "",
        "InstalledVersion": "",
        "FixedVersion": "",
        "Title": "",
        "Description": "",
        "Severity": "",
        "References": []
      }
    ]
  }
]
```

**Comment by hijak** [comment]
ah yes this is cool as long as im able to predict the name of the array with the list of vuns inside it im happy
