### ISSUE TITLE
poetry support

### ISSUE THREAD

**Issue by sobolevn** [knqyf263/trivy#41]
Hi @knqyf263! Thanks for building this tool.

It is awesome. But, I would like to suggest a new feature: `poetry` / `pyproject.lock` file support. Docs: https://github.com/sdispater/poetry

It is pretty much the same as `pipenv`.

We consider adding your tools to our project: https://github.com/wemake-services/wemake-django-template/issues/780 But we miss `poetry` support.

**Comment by knqyf263** [comment]
@sobolevn Thank you for reporting an issue! `poetry` will be supported by @masahiro331 
Could you please wait for a while?

**Comment by sobolevn** [comment]
Sure! Thanks 👍

**Comment by masahiro331** [comment]
@sobolevn 
I want you to teach me, should I also support pyproject.lock?

**Comment by sobolevn** [comment]
Yes, that's where exact versions are stored. 
But, this file is now named `poetry.lock`. `pyproject.lock` was a recent name changed in one of the latest releases.

You can have something like this:

```toml
[packages]
bad-tool = "*"
```

And in lock:

```json
[[package]]
category = "dev"
description = "Package with security issues"
name = "bad-tool"
optional = false
python-versions = "*"
version = "1.5.1"
```

**Comment by masahiro331** [comment]
@sobolevn 
Poetry supported.
please update trivy to [v.0.1.1](https://github.com/knqyf263/trivy/releases/tag/v0.1.1)

**Comment by knqyf263** [comment]
@sobolevn If you have any questions, please reopen this issue.
