### ISSUE TITLE
support for private registry protected by basic auth

### ISSUE THREAD

**Issue by negbie** [knqyf263/trivy#45]
Would it be possible to allow following url to support basic auth without having docker installed?

user:pw@url

**Comment by negbie** [comment]
or https://user:pw@url

**Comment by tomoyamachi** [comment]
We will support a registry require auth without install docker. (basic auth, ECR, GCR ...)
Please wait a while.

**Comment by tomoyamachi** [comment]
@negbie 
I did it.
Please check [Authorization for Private Docker Registry](https://github.com/knqyf263/trivy#authorization-for-private-docker-registry).

**Comment by negbie** [comment]
@tomoyamachi Thats awesome! Thank you so much!

**Comment by tomoyamachi** [comment]
@negbie Sorry, this feature available in the next release(v0.1.2).
Please wait for a moment.

**Comment by negbie** [comment]
@tomoyamachi No problem :) Thank you!

**Comment by tomoyamachi** [comment]
@negbie 
We released v0.1.2!

**Comment by negbie** [comment]
@tomoyamachi Great news and thank you very much for this!
