### ISSUE TITLE
Unknown os error

### ISSUE THREAD

**Issue by guanw** [knqyf263/trivy#59]
**Description**

Trying to run this tool against jaegertracing/all-in-one

**What did you expect to happen?**
Should run just fine

**What happened instead?**
got error

**Output of run with `-debug`:**

```
$ trivy jaegertracing/all-in-one:1.12
2019-05-25T21:59:43.389-0400	INFO	Updating vulnerability database...
2019-05-25T21:59:43.887-0400	FATAL	error in image scan: failed to scan image: failed to analyze OS: Unknown OS
```

**Output of `trivy -v`:**

```
trivy version 0.1.1
```

**Additional details (base image name, container registry info...):**
I'm not sure why the error is thrown. The docker file is here: `https://github.com/jaegertracing/jaeger/blob/master/cmd/all-in-one/Dockerfile`, doesn't  seem to specify os?

**Comment by tomoyamachi** [comment]
The `scratch` image is empty. So `trivy` can't detect OS.

**Comment by knqyf263** [comment]
As @tomoyamachi said, trivy doesn't support `scratch`.
Thanks.
