### ISSUE TITLE
trivy doesn't work without `rpm` on some distribution

### ISSUE THREAD

**Issue by checkelmann** [knqyf263/trivy#62]
**Description**

When using trivy to scan a docker image from centos:latest I'm getting this error:
```2019-05-28T12:48:44.679Z	FATAL	error in image scan: failed to scan image: failed to analyze OS packages: Unknown OS```

**What did you expect to happen?**
The scan will be performed

**What happened instead?**
Scan interrupted

**Output of run with `-debug`:**

```
 11122 / 11122  100.00%
 11122 / 11122  100.00%
 11122 / 11122  100.00% 0s
2019-05-28T13:05:46.351Z	DEBUG	OS family: centos, OS version: 7.6.1810
2019-05-28T13:05:46.367Z	FATAL	error in image scan:
    github.com/knqyf263/trivy/pkg.Run
        /root/project/pkg/run.go:160
  - failed to scan image:
    github.com/knqyf263/trivy/pkg/scanner.ScanImage
        /root/project/pkg/scanner/scan.go:53
  - failed to analyze OS packages:
    github.com/knqyf263/trivy/pkg/scanner/ospkg.Scan
        /root/project/pkg/scanner/ospkg/scan.go:51
  - Unknown OS:
    github.com/knqyf263/fanal/analyzer.init.ializers
        /go/pkg/mod/github.com/knqyf263/fanal@v0.0.0-20190521154631-a2dde7e171c6/analyzer/analyzer.go:24
ERROR: Job failed: exit code 1
```

**Output of `trivy -v`:**

```
$ trivy -v
trivy version 0.1.2
```

**Additional details (base image name, container registry info...):**
centos:latest

**Comment by tomoyamachi** [comment]
`trivy` requires a `rpm` command on Cent OS.
We will support RPM packages without `rpm` command soon.

**Comment by checkelmann** [comment]
Ok, got it was not so clear that the machine where trivy is being executed needs rpm as well.
