### ISSUE TITLE
Add S3 as a cache storage

### ISSUE THREAD

**Issue by computeralex92** [knqyf263/trivy#63]
After trying AWS EFS for a central cache folder for our building nodes I want to ask if there is an option to implement S3 for the cache storage?

EFS is to slow in special with small files and there are many storage systems compatible with the S3 API (Minio etc).

**Comment by FernandoMiguel** [comment]
It's only 4GB of downloaded data.
Why do you feel the need to keep a cache vs pulling it when you get a new
node?

We use spot instances, store the cache on ephemeral disks, and that works
quite well for us

--
Fernando Miguel

**Comment by computeralex92** [comment]
@FernandoMiguel That's right, I tested it today and it is working quite well.
Thanks for the hint
