### ISSUE TITLE
Getting sqlite & jdk vulnerability issues as part of alpine 3.9 

### ISSUE THREAD

**Issue by thirutibco** [knqyf263/trivy#78]
Getting vulnerability issues with sqlite, using alpine OS 3.9.0 version. I tried apk update, apk upgrade but still the version shows 3.26.0-r03 instead of showing the latest version 3.28.0-r0.
Anybody can help?

bash-4.4# apk info sqlite
WARNING: Ignoring APKINDEX.4e9201c8.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.4c67d94b.tar.gz: No such file or directory
sqlite-3.26.0-r3 description:
C library that implements an SQL database engine

sqlite-3.26.0-r3 webpage:
http://www.sqlite.org

sqlite-3.26.0-r3 installed size:

**Comment by thirutibco** [comment]
Getting vulnerability issues with sqlite, using alpine OS 3.9.0 version. I tried apk update, apk upgrade but still the version shows 3.26.0-r03 instead of showing the latest version 3.28.0-r0.
Anybody can help?


bash-4.4# apk info sqlite
WARNING: Ignoring APKINDEX.4e9201c8.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.4c67d94b.tar.gz: No such file or directory
sqlite-3.26.0-r3 description:
C library that implements an SQL database engine

sqlite-3.26.0-r3 webpage:
http://www.sqlite.org

sqlite-3.26.0-r3 installed size:

**Comment by knqyf263** [comment]
Duplicate https://github.com/knqyf263/trivy/issues/74

**Comment by knqyf263** [comment]
If you have any question, please reopen this issue.
