### ISSUE TITLE
Deb Update Broken

### ISSUE THREAD

**Issue by jgamblin** [knqyf263/trivy#79]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

You do NOT have to include this information if this is a FEATURE REQUEST
    
If this is a BUG REPORT, provide key information from your environment:

Ubuntu:18:04

apt-update tivy won't work

**What did you expect to happen?**
tivy to update

**What happened instead?**

Ign:4 https://knqyf263.github.io/trivy-repo/deb [CODE_NAME] InRelease
Err:5 https://knqyf263.github.io/trivy-repo/deb [CODE_NAME] Release
  404  Not Found [IP: 185.199.108.153 443]

**Comment by knqyf263** [comment]
Did you replacce [CODE_NAME] with your code name? (e.g. wheezy, jessie, etc.)

**Comment by jgamblin** [comment]
That was the case... I thought I had fixed it with an echo but did not.
