### ISSUE TITLE
docker image and binary semver mismatch

### ISSUE THREAD

**Issue by cgetzen** [knqyf263/trivy#83]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

Running trivy in a container (0.1.2 and 0.1.3) does not produce the semver that it does locally.
```
» docker run -it knqyf263/trivy:0.1.2 "--version"
trivy version dev
```

**What did you expect to happen?**

I expected it to output "trivy version 0.1.2"

**Comment by knqyf263** [comment]
@cgetzen I appreciate you for reporting the issue.
