### ISSUE TITLE
Add option just to refresh database

### ISSUE THREAD

**Issue by nunofernandes** [knqyf263/trivy#9]
Hello,

The command should also allow the refresh without an image being passed to be scanned:
To workaround this I just pass the scratch image but it fails with an error:

```
# /trivy -q --refresh scratch
....
2019-05-16T17:56:46.360Z	FATAL	error in image scan: failed to analyze image: failed to extract files: missing signature key
```

Is there a way just to refresh the database without passing an image? When I try to pass just the `--refresh` I get:

```
# /trivy -q --refresh
2019-05-16T19:03:13.273+0100    INFO    trivy" requires at least 1 argument or --input option.
NAME:
  trivy - A simple and comprehensive vulnerability scanner for containers
USAGE:
  trivy [options] image_name
...
```

**Comment by knqyf263** [comment]
@nunofernandes Thanks for your feedback! I enabled `--refresh` without specifying an image name.

**Comment by nunofernandes** [comment]
Thank you so much! Awsome!
