### ISSUE TITLE
FEAT: Compress the final binary using UPX

### ISSUE THREAD

**Issue by pascalandy** [knqyf263/trivy#95]
I'm proposing the make the final docker image smaller by using UPX in the Dockerfile.
I will also add several best practices to the Dockerfile.

This is how it looks like:

```
+ upx /usr/local/bin/trivy
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  26868298 ->  12844512   47.81%   linux/amd64   trivy

Packed 1 file.
+ upx -t /usr/local/bin/trivy
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

testing /usr/local/bin/trivy [OK]
```

Please just confirm that you have time to review before I submit a PR.

Cheers!

**Comment by knqyf263** [comment]
@pascalandy Thank you. I'm waiting for your PR!

**Comment by pascalandy** [comment]
Give me 2 days. Two events in a row over here :-p

**Comment by knqyf263** [comment]
Sure. I appreciate your help.

**Comment by pascalandy** [comment]
Please re-open. UPX is only one thing I want to add to the Dockerfile :)

> I will also add several best practices to the Dockerfile.

**Comment by knqyf263** [comment]
The title of this issue is "Compress the final binary using UPX". I think this issue has already been resolved. So, would you create another issue?

**Comment by pascalandy** [comment]
There we go https://github.com/knqyf263/trivy/pull/99
